### ISSUE TITLE
Warn of no vote even if vote is there

### ISSUE THREAD

**Issue by CheAle14** [TheGrandCoding/awardsprogram#20]
Probably to do with abdul's changes

**Comment by CheAle14** [comment]
@abdulshafiq0 indicated they would take a look at it to ensure it works.

**Comment by abdulshafiq2002** [comment]
Fixed with testing

**Comment by CheAle14** [comment]
Please refrain from closing issues outside of commit messages

**Comment by abdulshafiq2002** [comment]
commit 9c754f8 - fixed and tesed

**Comment by CheAle14** [comment]
![image](https://user-images.githubusercontent.com/12370876/50348723-8c7c3f00-0531-11e9-8fe5-520539d7f58b.png)
That certainly didn't fix it

Fixed in 5d862b4ab3f

**Comment by abdulshafiq2002** [comment]
oops sorry wrong commit 9c754f8 with the b969b41

**Comment by abdulshafiq2002** [comment]
how the hell did that comment (5d862b4) fix anything all you did was log more stuff

**Comment by CheAle14** [comment]
![image](https://user-images.githubusercontent.com/12370876/50348907-0dd3d180-0532-11e9-851b-8224f9af4283.png)
The issue was because the text was being set to "", it was removing the `CurrentCategory.FirstWinner` prior to it being set again in the `RefreshCategoryUI()` function.
